# Generated by Django 4.1.5 on 2023-01-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='orders',
            field=models.ManyToManyField(to='api.orders'),
        ),
    ]
