# Generated by Django 4.1.5 on 2023-01-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='orders_items',
            field=models.ManyToManyField(null=True, to='api.orders_items'),
        ),
    ]
