# Generated by Django 4.1.5 on 2023-01-06 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_orders_orders_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='orders_items',
            field=models.ManyToManyField(to='api.orders_items'),
        ),
        migrations.AlterField(
            model_name='orders_items',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.items'),
        ),
        migrations.AlterField(
            model_name='user',
            name='orders',
            field=models.ManyToManyField(to='api.orders'),
        ),
    ]
