# Generated by Django 4.1.5 on 2023-01-07 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_orders_orders_items_alter_orders_items_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders_items',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.items'),
        ),
    ]
